<!DOCTYPE HTML>
<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<link rel="stylesheet" type="text/css"
    href="http://static.phpcloud.com/styles/blueprint/screen.css"
	type="text/css" media="screen, projection">
<link rel="stylesheet" type="text/css"
	href="http://static.phpcloud.com/styles/blueprint/print.css"
	type="text/css" media="print">
<link rel="stylesheet" type="text/css"
	href="http://static.phpcloud.com/styles/cloud.css" type="text/css"
	media="screen, projection">
<script type="text/javascript"
	src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>

<title>Develop, Deploy and Manage PHP Applications in the Cloud</title>
<script type="text/javascript"
	src="http://static.phpcloud.com/scripts/fancybox/jquery.fancybox-1.3.4.pack.js"></script>
<script type="text/javascript"
	src="http://static.phpcloud.com/scripts/nivo-slider/jquery.nivo.slider.pack.js"></script>
<link
	href="http://static.phpcloud.com/scripts/nivo-slider/themes/default/default.css"
	media="screen" rel="stylesheet" type="text/css" />
<link
	href="http://static.phpcloud.com/scripts/nivo-slider/themes/pascal/pascal.css"
	media="screen" rel="stylesheet" type="text/css" />
<link
	href="http://static.phpcloud.com/scripts/nivo-slider/themes/orman/orman.css"
	media="screen" rel="stylesheet" type="text/css" />
<link
	href="http://static.phpcloud.com/scripts/nivo-slider/nivo-slider.css"
	media="screen" rel="stylesheet" type="text/css" />
<link
	href="http://static.phpcloud.com/scripts/fancybox/jquery.fancybox-1.3.4.css"
	media="screen" rel="stylesheet" type="text/css" />
</head>

<body>
	<div id="header_wrapper">
		<div id="global_header" style="width:450px;margin:0 auto;">
			<div id="logo" style="margin-top: 10px;">
				<a href="/"> <img
					src="http://static.phpcloud.com/images/phpcloud-logo-transparency-with-TM.png" />
				</a>
			</div>

		</div>
	</div>

	<script type="text/javascript">
		$(document).ready( function() {
			$.ajax({
				type : "GET",
				url : "index.php/index/twitter",
				success : function(data, textStatus) {
					$('#tweets').html(data);
				},
			});
		});
	</script>


	<br/>
	
	<div class="trio-text" id="tweets"></div>

	<style>
	.trio-text {
		font-size: 28px;
		color: #EFEFFF;
		font-weight: bold;
		font-family: trebucet;
		padding-left: 100px;
	}
	.trio-icon{
		float:left;
		width:50px;
		height:50px;	
	}
</style>
	<center>
		<div style="font-size: x-large; ">Tweets for #zendcon at 
			<?php 
				echo dat("Y/d/m") 
			?>
		</div>
	</center>
	
	


</body>


</html>
